#ifndef _SMARTRF_SETTINGS_BLE_H_
#define _SMARTRF_SETTINGS_BLE_H_


//*********************************************************************************
// Generated by SmartRF Studio version 2.13.0 (build #164)
// Tested for SimpleLink SDK version: CC13x2 SDK 2.40.xx.xx
// Device: CC1352R Rev. 2.1
//
//*********************************************************************************

#include <ti/devices/DeviceFamily.h>
#include DeviceFamily_constructPath(driverlib/rf_mailbox.h)
#include DeviceFamily_constructPath(driverlib/rf_common_cmd.h)
#include DeviceFamily_constructPath(driverlib/rf_ble_cmd.h)
#include <ti/drivers/rf/RF.h>


// TX Power table size definition
#define RF_BLE_TX_POWER_TABLE_SIZE 11

// TX Power Table Object
extern RF_TxPowerTable_Entry RF_BLE_txPowerTable[];

// TI-RTOS RF Mode Object
extern RF_Mode RF_modeBle;

// RF Core API commands
extern rfc_CMD_BLE5_RADIO_SETUP_t RF_ble_cmdRadioSetup;
extern rfc_CMD_FS_t RF_ble_cmdFs;
extern rfc_bleAdvPar_t bleAdvPar;
extern rfc_CMD_BLE_ADV_NC_t RF_ble_cmdBleAdvNc;
extern rfc_CMD_BLE5_ADV_AUX_t RF_ble_cmdBle5AdvAux;
extern rfc_CMD_BLE5_GENERIC_RX_t RF_ble_cmdBleGenericRx;  //For backward compatibility

// RF Core API Overrides
extern uint32_t pOverridesCommon[];
extern uint32_t pOverrides1Mbps[];
extern uint32_t pOverrides2Mbps[];
extern uint32_t pOverridesCoded[];

#endif // _SMARTRF_SETTINGS_BLE_H_
